---
abstract: 'Schema for CPAN Meta'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
generated_by: 'Dist::Zilla version 1.093000'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Schema-Schema-CPANMeta
requires:
  Data::Schema: 0
  File::Slurp: 0
  FindBin: 0
  Storable: 0
  Test::More: 0
  YAML::XS: 0
version: 0.03
